/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.AluguelDAO;
import DAO.ClienteDAO;
import DAO.LivroDAO;
import DTO.AluguelDTO;
import DTO.ClienteDTO;
import DTO.LivroDTO;
import javax.swing.JOptionPane;
import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class formAluguelVIEW extends javax.swing.JFrame {

    /**
     * Creates new form formAluguelVIEW
     */
    public formAluguelVIEW() {
        initComponents();
        setLocationRelativeTo(null);
        listarClientes();
        listarLivros();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_pesquisarCliente = new javax.swing.JLabel();
        cbox_listaClientes = new javax.swing.JComboBox<>();
        cbox_periodoAluguel = new javax.swing.JComboBox<>();
        btn_voltarHome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_listaLivros = new javax.swing.JTable();
        btn_alugarLivro = new javax.swing.JButton();
        btn_gerenciarAlugueis = new javax.swing.JButton();
        lbl_tituloGerenciamento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(120, 23, 30));

        jPanel1.setBackground(new java.awt.Color(48, 48, 48));

        lbl_pesquisarCliente.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lbl_pesquisarCliente.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pesquisarCliente.setText("Pesquisar cliente:");

        cbox_periodoAluguel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Período", "7 dias", "14 dias", "21 dias", "30 dias" }));

        btn_voltarHome.setBackground(new java.awt.Color(150, 150, 150));
        btn_voltarHome.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_voltarHome.setForeground(new java.awt.Color(255, 255, 255));
        btn_voltarHome.setText("Voltar");
        btn_voltarHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarHomeActionPerformed(evt);
            }
        });

        tbl_listaLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISBN", "Título", "Autor", "Quantidade disponível"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_listaLivros);

        btn_alugarLivro.setBackground(new java.awt.Color(150, 150, 150));
        btn_alugarLivro.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_alugarLivro.setForeground(new java.awt.Color(255, 255, 255));
        btn_alugarLivro.setText("Alugar");
        btn_alugarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alugarLivroActionPerformed(evt);
            }
        });

        btn_gerenciarAlugueis.setBackground(new java.awt.Color(150, 150, 150));
        btn_gerenciarAlugueis.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btn_gerenciarAlugueis.setForeground(new java.awt.Color(255, 255, 255));
        btn_gerenciarAlugueis.setText("Gerenciar aluguéis");
        btn_gerenciarAlugueis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerenciarAlugueisActionPerformed(evt);
            }
        });

        lbl_tituloGerenciamento.setBackground(new java.awt.Color(250, 255, 0));
        lbl_tituloGerenciamento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_tituloGerenciamento.setForeground(new java.awt.Color(250, 255, 0));
        lbl_tituloGerenciamento.setText("GESTÃO DE ALUGUÉIS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btn_alugarLivro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_gerenciarAlugueis, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1)
                        .addComponent(lbl_pesquisarCliente)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(cbox_listaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cbox_periodoAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_tituloGerenciamento)
                        .addGap(192, 192, 192)
                        .addComponent(btn_voltarHome)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_voltarHome)
                    .addComponent(lbl_tituloGerenciamento))
                .addGap(18, 18, 18)
                .addComponent(lbl_pesquisarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_listaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox_periodoAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_alugarLivro)
                    .addComponent(btn_gerenciarAlugueis))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_alugarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alugarLivroActionPerformed
        alugarLivro();
        listarLivros();
    }//GEN-LAST:event_btn_alugarLivroActionPerformed

    private void btn_voltarHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarHomeActionPerformed
        formHomeVIEW objFormHomeVIEW = new formHomeVIEW();
        dispose();
        objFormHomeVIEW.setVisible(true);
    }//GEN-LAST:event_btn_voltarHomeActionPerformed

    private void btn_gerenciarAlugueisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerenciarAlugueisActionPerformed
        formGerenciarAluguelVIEW objFormGerenciarAluguelVIEW = new formGerenciarAluguelVIEW();
        dispose();
        objFormGerenciarAluguelVIEW.setVisible(true);
    }//GEN-LAST:event_btn_gerenciarAlugueisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formAluguelVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formAluguelVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formAluguelVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formAluguelVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formAluguelVIEW().setVisible(true);
            }
        });
    }

    private void alugarLivro() {
        try {
            int matricula, periodo = 0;
            String isbn = "";
            ClienteDAO objClienteDAO = new ClienteDAO();
            LivroDAO objLivroDAO = new LivroDAO();
            AluguelDTO objAluguelDTO = new AluguelDTO();
            matricula = collectMatricula();
            isbn = collectISBN();
            if (isbn.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Selecione um livro para empréstimo.", "Selecione um Livro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String selectedItem = (String) cbox_periodoAluguel.getSelectedItem();
            switch (selectedItem) {
                case "7 dias":
                    selectedItem = "7";
                    break;
                case "14 dias":
                    selectedItem = "14";
                    break;
                case "21 dias":
                    selectedItem = "21";
                    break;
                case "30 dias":
                    selectedItem = "30";
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Selecione um período de empréstimo.", "Selecione o período", JOptionPane.ERROR_MESSAGE);
                    return;
            }
            periodo = Integer.parseInt(selectedItem);

            ClienteDTO objClienteDTO = objClienteDAO.pesquisarClienteMatricula(matricula);
            LivroDTO objLivroDTO = objLivroDAO.pesquisarLivroISBN(isbn);
            objAluguelDTO.setId_cliente(objClienteDTO.getId_cliente());
            objAluguelDTO.setId_livro(objLivroDTO.getId_livro());
            objAluguelDTO.setData_aluguel(Date.valueOf(LocalDate.now()));
            objAluguelDTO.setData_devolucao(Date.valueOf(LocalDate.now().plusDays(periodo)));
            AluguelDAO objAluguelDAO = new AluguelDAO();
            if (objAluguelDAO.pesquisarAluguelPorLinha(objAluguelDTO) != null) {
                JOptionPane.showMessageDialog(this, "O cliente já tem uma reserva igual.", "Reserva já existe", JOptionPane.ERROR_MESSAGE);
                return;
            }
            objAluguelDAO.cadastrarAluguel(objAluguelDTO);
            objLivroDAO.atualizarQuantidadeDisponivel(objLivroDTO, true);
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "formAluguelVIEW - alugarLivro(): " + erro);
        }

    }

    private int collectMatricula() {
        int matricula = 0;
        try {
            String selectedItem = (String) cbox_listaClientes.getSelectedItem();
            if (selectedItem != null) {
                String[] parts = selectedItem.split(" - ");
                matricula = Integer.parseInt(parts[0]);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "collectMatricula()" + erro);
        }
        return matricula;
    }

    private String collectISBN() {
        String isbn = "";
        try {
            int rowIndex = tbl_listaLivros.getSelectedRow();
            if (rowIndex != -1) {
                isbn = (String) tbl_listaLivros.getValueAt(rowIndex, 0);
            }
        } catch (Exception e) {
        }
        return isbn;
    }

    private void listarClientes() {
        try {
            ClienteDAO objClienteDAO = new ClienteDAO();
            this.cbox_listaClientes.removeAllItems();
            ArrayList<ClienteDTO> clientList = objClienteDAO.pesquisarCliente();
            for (ClienteDTO cliente : clientList) {
                String item = cliente.getMatricula() + " - " + cliente.getNome();
                this.cbox_listaClientes.addItem(item);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listarClientes(): " + erro);
        }
    }

    private void listarLivros() {
        try {
            LivroDAO objLivroDAO = new LivroDAO();
            DefaultTableModel model = (DefaultTableModel) tbl_listaLivros.getModel();
            model.setNumRows(0);
            ArrayList<LivroDTO> bookList = objLivroDAO.listarLivros();
            for (int num = 0; num < bookList.size(); num++) {
                model.addRow(new Object[]{
                    bookList.get(num).getIsbn(),
                    bookList.get(num).getTitulo(),
                    bookList.get(num).getAutor(),
                    bookList.get(num).getQnt_disponivel()
                });
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "formAluguelVIEW - listarLivros(): " + erro);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_alugarLivro;
    private javax.swing.JButton btn_gerenciarAlugueis;
    private javax.swing.JButton btn_voltarHome;
    private javax.swing.JComboBox<String> cbox_listaClientes;
    private javax.swing.JComboBox<String> cbox_periodoAluguel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_pesquisarCliente;
    private javax.swing.JLabel lbl_tituloGerenciamento;
    private javax.swing.JTable tbl_listaLivros;
    // End of variables declaration//GEN-END:variables
}
